---
title: "o-well #1"
author: "Quynh Tran  [quynh_tran]"
output: html_document
---

# Set up folder
```{r}
which.github = "local";

github.local = "/Users/quynhtrann248/Dropbox/-stat419-quynh_tran/";
github.remote = "https://github.com/quynh-tran419/WSU_STAT419/tree/master/"

if(which.github == "remote")
  {
  mypath =paste0(github.remote,"/workspace/o-well/")
  # include.me = paste0( github.remote, "functions-intro.R");
  # library(devtools);
  # source_url(include.me);
  } else {
    mypath = paste0(github.local,"/workspace/o-well/")
      # include.me = paste0( github.local, "functions/functions-intro.R");
      # source(include.me)
  }

path = paste0(github.local,"/workspace/o-well/");
```



```{r}

path.data = paste0(mypath, "dataset/")

```


# Extract data and appending extra data
```{r}
library(tabulizer)

# Extracting table 1 - Statistics for dissolved metals results of groundwater samples, with the information of only 23 wells

table_1 <- extract_tables(file ="/Users/quynhtrann248/Dropbox/-stat419-quynh_tran/workspace/o-well/dataset/Well-23.pdf",pages = 7)
owell.metals <- data.frame(table_1)
owell.metals = owell.metals[-c(26:31),]   # removing rows 26-31
owell.metals = owell.metals[,-c(1)]       # removing the first column
names(owell.metals) <- owell.metals[1,]   # making the first row the header
owell.metals = owell.metals[-c(1,2),]     # removing the first and second rows
rownames(owell.metals) = NULL             # removing rowname


# Similarly, extracting and tidying up table 2- Statistics for physical and chemical parameters of groundwater samples.
table_2 <- extract_tables(file ="/Users/quynhtrann248/Dropbox/-stat419-quynh_tran/workspace/o-well/dataset/Well-23.pdf",pages = 8, output = "data.frame")
owell.chemistry <- data.frame(table_2[1])
owell.chemistry = owell.chemistry[-c(19:22,28:31),]
owell.chemistry = owell.chemistry[-c(1),]
owell.chemistry = owell.chemistry[,-c(1)]
rownames(owell.chemistry) = NULL


# read wells location with latitude, longitude, and altitude. 
# Modify the read in data by splitting the data to columns by each "|" and activating header
wells_location <- read.delim(file = "/Users/quynhtrann248/Dropbox/-stat419-quynh_tran/workspace/o-well/dataset/wells-location.txt", sep = "|", header = TRUE, quote ="")
wells_location = data.frame(wells_location)

# create fault data frame, which estimates in "meters" a value for each well as a nearest distance to a fault
fault <- c(1208.136649,421.8996184,421.8996184,1509.433962,421.8996184,1555.888915,1016.068832,1132.075472,1623.080239,1132.075472,377.3584906,1132.075472,2109.498092,2005.687889,1360.585387,566.0377358,943.3962264,3207.54717,777.9444577,754.7169811,843.7992368,1886.792453,188.6792453)

# create geology data frame, which contains the first word of relevant rock formations near the wells
geology <- c("Sand","Sand, Alkaline, Granite","Alkaline,Conglomerate","Alkaline","Volcanic rock,Granite","Volcanic rock","Gypsum","Gypsum","Alkaline","Gypsum","Volcanic rock","Alkaline,Granite","Granite","Gypsum","Gypsum","Volcanic rock","Alkaline,Granite,Volcanic rock","Conglomerate,Gypsum","Sand","Sand","Sand","Sand","Sand")

geology = data.frame(geology)
fault = data.frame(fault)


# binding wells_location, fault data, and geology dataframe to table_1 (owell.metals) and table_2 (owell.chemistry)
owell.metals <- cbind(owell.metals, wells_location)
owell.metals <- cbind(owell.metals,fault)
owell.metals <- cbind(owell.metals, geology)
owell.chemistry <- cbind(owell.chemistry, wells_location)
owell.chemistry <- cbind(owell.chemistry, fault)
owell.chemistry <- cbind(owell.chemistry,geology)
```


# Create and save list named wells as well.rds file. This list is to call the dataframes without having to run the code above.
```{r}

wells = list();
	wells$saudi = list();
	wells$saudi$metals = owell.metals;
	wells$saudi$chemistry = owell.chemistry
saveRDS(wells, file ="wells.rds")
readRDS(file = "wells.rds")

```


